# NUMPY Creating Arrays

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([1, 2, 3, 4], ndmin=2)

In [6]:
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

1


# NUMPY Indexing Arrays

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[4])

50


In [4]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1, 0])

50


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


# NUMPY Slicing Arrays

In [2]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:4])

[15 20 25]


In [2]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[2:4])

[20 25]


In [3]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:4:2])

[15 25]


In [4]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

[10 20 30 40]


# NUMPY Data Types

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [6]:
arr = np.array([1, 2, 3, 4], dtype='S')

In [7]:
print(arr)

[b'1' b'2' b'3' b'4']


In [8]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

# NUMPY Copy Vs View

In [3]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
x=arr.copy()
print(x)

[1 2 3 4 5]


In [5]:
arr = np.array([1, 2, 3, 4, 5])
x=arr.view()
print(x)

[1 2 3 4 5]


# NUMPY Array Shape

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)


In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)


In [14]:
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
newarr = arr.reshape(-1)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# NUMPY Joining Array

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

# NUMPY Array Search

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)